


export const listGPT = [{
    image: require('./assets/icon/logo-gpt.jpg'),
    title: 'html gpt',
    tags: ['code', 'html', 'design', 'structure'],
    description: 'Un generador de código capaz de diseñar código en varios lenguajes de programación',
    labels: {
        author: 'owner',
        download: '20k'
    }
},{
    image: require('./assets/icon/logo-gpt.jpg'),
    title: 'data gpt',
    tags: ['bi', 'pb', 'crm', 'erp'],
    description: 'Un analizador de código capaz de interpretar graficas y obtener resultados',
    labels: {
        author: 'owner',
        download: '20k'
    }
},{
    image: require('./assets/icon/logo-gpt.jpg'),
    title: 'docs gpt',
    tags: ['docs', 'drive', 'data'],
    description: 'Un drive universal para los recursos de tu ordenador en la nube',
    labels: {
        author: 'owner',
        download: '20k'
    }
},{
    image: require('./assets/icon/logo-gpt.jpg'),
    title: 'flow gpt',
    tags: ['flow', 'diagram', 'brain'],
    description: 'Un diagrama para obtener datos sobre mapas mentales',
    labels: {
        author: 'owner',
        download: '20k'
    }
},{
    image: require('./assets/icon/logo-gpt.jpg'),
    title: 'eye gpt',
    tags: ['ai', 'modern', 'science', 'art'],
    description: 'Con una imagen de tus ojos descubre el universo de información de tus ojos',
    labels: {
        author: 'owner',
        download: '20k'
    }
}]



export const listTools = [{
    image: require('./assets/icon/essay-writer.svg').default,
    title: 'AI Essay Writer',
    description: 'Write a professional essay with an in-depth vision, covering everything and using any reference style you need.'
},{
    image: require('./assets/icon/essaychecker.svg').default,
    title: 'Essay Checker',
    description: 'Verify the organization, clarity, and overall quality of an essay to ensure proper structure.'
},{
    image: require('./assets/icon/essayrewriter-icon-01.svg').default,
    title: 'Essay Rewriter',
    description: 'Rewrite your essay to make it plagiarism-free and convey a stronger sense of professionalism.'
},{
    image: require('./assets/icon/hook-generator.svg').default,
    title: 'Essay Hook Generator',
    description: 'Hook your readers from the start with our AI-powered essay hook generator.'
},{
    image: require('./assets/icon/essay-extender.svg').default,
    title: 'Essay Extender',
    description: 'Expand your essay content to deepen your arguments and broaden your discussions.'
},{
    image: require('./assets/icon/essay-introduction.svg').default,
    title: 'Essay Introduction Generator',
    description: 'Make a lasting first impression with our AI-powered essay introduction generator.'
},



{
    image: require('./assets/icon/research-paper.svg').default,
    title: 'Research Paper Summarizer',
    description: 'Simplify complex research with AI-driven summaries, enhancing productivity and comprehension alike.'
},{
    image: require('./assets/icon/casestudy-icon-01.svg').default,
    title: 'Case Study Summarizer',
    description: 'Condense case studies into concise insights, empowering data-driven decision learning.'
},{
    image: require('./assets/icon/conclusiongenerator.svg').default,
    title: 'Essay Conclusion Generator',
    description: 'Wrap up your writing with impactful, resonant conclusions generated by AI.'
},{
    image: require('./assets/icon/thesisstatement-icon-01.svg').default,
    title: 'Thesis Statement Generator',
    description: 'Level up your academic writing with excellent thesis statements.'
},{
    image: require('./assets/icon/research-title-generator.svg').default,
    title: 'Research Title Generator',
    description: 'Unlock your research potential with our cutting-edge Research Title Generator.'
},{
    image: require('./assets/icon/essayshortener-icon-01.svg').default,
    title: 'Essay Shortener',
    description: 'Transform lengthy essays into concise, impactful pieces with AI-driven content reduction.'
},




{
    image: require('./assets/icon/paraphrasingtool.svg').default,
    title: 'Paraphrasing Tool',
    description: 'Advanced paraphrasing tool that not just simply rephrases your content but also enhances its overall quality.'
},{
    image: require('./assets/icon/article-rewrite.svg').default,
    title: 'Article Rewriter',
    description: 'Rewrite and transform your article into an irresistible masterpiece that captivates readers and preserves its originality.'
},{
    image: require('./assets/icon/summarizer.svg').default,
    title: 'Text & PDF Summarizer',
    description: 'Identify and correct grammatical errors to improve clarity, conciseness, and credibility in any written work.'
},{
    image: require('./assets/icon/ai-paragraph-rewrite.svg').default,
    title: 'AI Paragraph Rewriter',
    description: 'Refresh and enhance your paragraphs for better readability and audience engagement.'
},{
    image: require('./assets/icon/profreader.svg').default,
    title: 'Proofreader',
    description: 'Revise a text for grammar, spelling, punctuation, or formatting errors to enhance clarity.'
},


{
    image: require('./assets/icon/ai-email.svg').default,
    title: 'AI Email Writer',
    description: 'Create personalized and engaging emails quickly and easily with our advanced AI-power tool.'
},{
    image: require('./assets/icon/ai-email.svg').default,
    title: 'Email Subject Line Generator',
    description: 'Create captivating and optimized email subject lines to give your business a boost.'
},{
    image: require('./assets/icon/coldemail-icon-01.svg').default,
    title: 'Cold Email Generator',
    description: 'Increase response rates with compelling cold emails, opening doors to new business opportunities.'
},{
    image: require('./assets/icon/marketing-email.svg').default,
    title: 'Marketing Email Generator',
    description: 'Boost your campaigns with eye-catching marketing emails, optimized for conversion.'
},{
    image: require('./assets/icon/thank-you-letter.svg').default,
    title: 'Thank You Letter Generator',
    description: 'Show your appreciation with heartfelt thank you letters tailored to your needs.'
},


{
    image: require('./assets/icon/hashtaggenerate.svg').default,
    title: 'Hashtag Generator',
    description: 'Generate creative and relevant hashtags to amplify your contents reach.'
},{
    image: require('./assets/icon/tweet-generator.svg').default,
    title: 'Tweet & Threads Generator',
    description: 'Make entertaining tweets to keep your followers interested.'
},{
    image: require('./assets/icon/facebook-generator.svg').default,
    title: 'Facebook Ad Copy Generator',
    description: 'Elaborate appealing copy based on your needs of Facebook Ads copy text.'
},{
    image: require('./assets/icon/scriptgenerator-icon-01.svg').default,
    title: 'Script Generator',
    description: 'Attract your audience with unique and compelling scripts that reflect your personality.'
},{
    image: require('./assets/icon/company-biogenerator.svg').default,
    title: 'Company Bio Generator',
    description: 'Write appealing and convincing bios that will arise your readers interest.'
},{
    image: require('./assets/icon/linkedin-generator.svg').default,
    title: 'Linkedin Headline Generator',
    description: 'Distinguish your LinkedIn profile with a compelling headline.'
},{
    image: require('./assets/icon/linkedin-generator.svg').default,
    title: 'Google Ad Copy Generator',
    description: 'Develop effective descriptions for your Google Search Ads to increase conversion.'
},


{
    image: require('./assets/icon/product-design.svg').default,
    title: 'Product Description Generator',
    description: 'Craft engaging, persuasive descriptions using AI-generated content.'
},{
    image: require('./assets/icon/amazon-icon-01.svg').default,
    title: 'Amazon Product Description Generator',
    description: 'Drive sales with SEO-optimized descriptions, maximizing visibility and customer engagement.'
},{
    image: require('./assets/icon/shopify-icon-01.svg').default,
    title: 'Shopify Product Description Generator',
    description: 'Optimize your Shopify store with persuasive descriptions and elevate your brand.'
},{
    image: require('./assets/icon/etsy-icon-01.svg').default,
    title: 'Etsy Product Description Generator',
    description: 'Entice potential buyers on Etsy with informative product descriptions that reflect your passion and creativity.'
},{
    image: require('./assets/icon/testimonialgenerator-icon-01.svg').default,
    title: 'Testimonials / Reviews Generator',
    description: 'Boost credibility with authentic, persuasive testimonials, attracting customers and fostering trust.'
},{
    image: require('./assets/icon/storyideagenerator-icon-01.svg').default,
    title: 'Store Description Generator',
    description: 'Define your store with a unique, engaging description, effortlessly conveying its value proposition.'
},{
    image: require('./assets/icon/flipkart-icon-01.svg').default,
    title: 'Flipkart Product Description Generator',
    description: 'Enhance your listings with captivating descriptions, enticing customers to choose your products.'
},{
    image: require('./assets/icon/features-benefit.svg').default,
    title: 'Features to Benefit Converter',
    description: 'Highlighting the features of your product as well as benefits to boost sales.'
},{
    image: require('./assets/icon/value-proposition.svg').default,
    title: 'Value Proposition Generator',
    description: 'Create a strong statement that describes the nature of your product and highlights its significance.'
},{
    image: require('./assets/icon/productfeaturesgenerator.svg').default,
    title: 'Product Features Generator',
    description: 'Create detailed and enticing descriptions of your products features, potentially improving your product visibility and driving more sales.'
},{
    image: require('./assets/icon/product-name-generator.svg').default,
    title: 'Product Name Generator',
    description: 'Create unique, catchy names for your product, capturing its essence and sparking customer interest.'
},{
    image: require('./assets/icon/cus-ai-business-name-generator.svg').default,
    title: 'AI Business Name Generator',
    description: 'Use artificial intelligence to design distinct and memorable business names that resonate with your target audience.'
}]